export default {
  nav: { overview: "总览", architecture: "系统架构", assets: "数据资产", decisions: "决策台", discipline: "实盘纪律", about: "关于" },
  common: { language: "语言", theme: "主题", themeProduct: "产品", themeArchitecture: "架构", themeTerminal: "终端" },
  overview: { title: "钱博士 Agent", heroStatus: "系统状态", trustData: "信任数据", pipelineRunning: "Pipeline 运行中", pipelineStopped: "Pipeline 未运行", lastChecked: "最近检查", detectedToday: "今日检测 {{count}} 个新视频", latestBrief: "最新简报", loading: "加载中…" },
  pages: {
    phaseOne: "Phase 1 实现",
    architecture: { title: "系统架构", subtitle: "从内容采集到决策复盘的自动化投研流水线", loading: "加载中…", unavailable: "实时数据暂不可用", live: "流水线实时状态", scheduler: "调度器", schedulerDetail: "流水线运行状态", lastChecked: "最近检查", queue: "队列", activity: "活动量", activityDetail: "今日检测 / 累计处理", pipelineTitle: "七层流水线", empty: "暂无架构数据", lifecycleTitle: "单条观点的生命周期", lifecycleSubtitle: "一条观点如何从视频变成可复盘的决策证据", mcpTitle: "MCP 工具", mcpSubtitle: "把投研资产暴露给 Agent，9 个工具实时查询" },
    discipline: { loading: "加载中…", error: "实盘纪律数据暂时不可用。", empty: "暂无实盘纪律数据", principlesLabel: "纪律原则", statsLabel: "复盘统计", statTotal: "总决策", statOpen: "待到期", statReviewed: "已复盘", statHit: "命中", statWrong: "未命中", coverage: "复盘覆盖率 {{value}}%", dataSource: "数据口径：user_decision_logs + decision_reviews", frameworkTitle: "实盘纪律框架", frameworkSubtitle: "情绪定方向 · 纪律定仓位 · 止损定退出", active: "生效中", logsTitle: "决策日志", logsSubtitle: "保留当时的判断，不展示事后结论；持仓与金额已脱敏", timelineTitle: "纪律时间线", conviction: "置信度", review: "复盘", return: "区间收益", window: "{{count}}天窗口", statusOpen: "待到期", statusReviewed: "已复盘", resultHit: "命中", resultWrong: "未命中", noThesis: "暂无核心逻辑", directionBullish: "看多", directionBearish: "看空", directionNeutral: "中性", horizonShort: "短期", horizonMedium: "中期", horizonLong: "长期" }
  },
  briefs: { title: "简报", description: "由内容采集、GPU 转写、结构化分析与 RAG 流程持续生成的每日盘前投研产物。", empty: "暂无简报", notFound: "未找到该简报", back: "返回", backToList: "返回简报列表", all: "全部简报", date: "日期", size: "大小", generatedAt: "生成时间", statTotal: "累计简报", statLatest: "最近更新", statCoverage: "覆盖时间", pieces: "篇", generated: "已生成", realOutput: "真实运行产出", sections: "章节", copyLink: "复制链接", copied: "已复制", prev: "上一篇", next: "下一篇", toc: "本页目录", preview: "内容预览" },
  market: { title: "全球市场 · Global Markets", updated: "数据更新", updatedAt: "数据更新 {{date}}", source: "来源", change: "涨跌", decisionValidation: "决策验证", bullish: "看多", bearish: "看空", neutral: "中性", pendingReview: "待复盘", reviewed: "已复盘", noData: "暂无行情数据", empty: "暂无行情数据", usAiStocks: "美股 AI 链", cnIndices: "A股指数", proxyAssets: "持仓代理 · 决策验证", dow: "道琼斯", nasdaq: "纳斯达克", sp500: "标普500" },
  decisions: { title: "决策台", description: "基于结构化观点库的用户决策记录、资产卡因子状态与到期自动复盘闭环。", statTotal: "决策总数", statOpen: "待复盘", statReviewed: "已复盘", statHit: "命中", statWrong: "失误", statsLabel: "决策统计", logTitle: "决策日志", cardsTitle: "资产卡", reviewsTitle: "复盘闭环", directionBullish: "看多", directionBearish: "看空", directionNeutral: "中性", statusOpen: "待复盘", statusReviewed: "已复盘", resultHit: "命中", resultWrong: "失误", horizonShort: "短期", horizonMedium: "中期", horizonLong: "长期", conviction: "信心度", reviewDate: "复盘", outcomeReturn: "收益", horizonDays: "{{count}} 日窗口", assetType: { commodity: "商品", sector: "板块", theme: "主题" }, loading: "正在加载决策数据…", error: "决策数据暂时不可用。", empty: "暂无决策数据", noReviews: "暂无到期复盘", noThesis: "暂无核心逻辑", noDescription: "暂无资产描述", generatedAt: "数据更新于" },
  metrics: { structuredViews: { label: "结构化观点", hint: "结构化观点库 JSONL 行数" }, predictionEvents: { label: "回测预测事件", hint: "SQLite prediction_events 表，到期自动复盘" }, notes: { label: "研究笔记", hint: "Obsidian 笔记库" }, ragChunks: { label: "知识库规模", hint: "ChromaDB RAG 向量库 chunks" } },
  dataAssets: { title: "数据资产", description: "观点库、分析师命中率与来源分布的结构化快照。", noData: "暂无数据" }
};